// Generates api/lib/eversdk-wasm-b64.ts from @eversdk/lib-web/eversdk.wasm.
// Runs in npm postinstall (Vercel too) so the wasm never needs to be
// traced by nft — it ships as a plain ESM string module.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const wasmPath = path.resolve(__dirname, '../node_modules/@eversdk/lib-web/eversdk.wasm');
const outPath = path.resolve(__dirname, '../api/lib/eversdk-wasm-b64.ts');
const b64 = readFileSync(wasmPath).toString('base64');
writeFileSync(outPath, `// generated by scripts/embed-wasm.mjs — do not edit\nconst wasmBase64 = '${b64}';\nexport default wasmBase64;\n`);
console.log('wasm embedded:', b64.length, 'b64 chars');
